### ISSUE TITLE
(TF-BR-002) - Facebook Login Error

### ISSUE THREAD

**Issue by ArikB21** [JerrelLustre/TidalFest#19]
**Status:** Open

**Assignee:** 

**Severity:** high

**Priority:** low

**Description:**

When logging in with the Facebook third-party authenticator, the user is unable to proceed. This works correctly for the other listed options (GitHub/Google+).

**Configuration/Setup:**

- Make sure to clear caching or open in an incognito tab
- Open https://tidalfestmusicfestival.emily-boyd.com/ and be at it's landing page
- Click on the "Login" button in the top right of the navigation bar.
- Click on the Facebook icon at the bottom underneath the "or sign-in with:" message

**Expected Result:** The user should be able to log-in normally after selecting their Facebook account and giving permissions.

**Actual Result:** There is a pop-up window that displays a message that says: "App not active". User is unable to select an account or continue and must click ok to return to the Log-in screen. Image is attached that shows the message in full.

![Image](https://user-images.githubusercontent.com/126725560/259283450-96190570-1380-40fe-9b8b-86fac2b599d1.PNG)

**Comment by Boyderr** [comment]
- App needs to be reviewed by Meta before being approved
- Review process takes up to 10 days
- Removing Facebook login/signup function as review process is too long
