### ISSUE TITLE
Code lineup page

### ISSUE THREAD

**Issue by jennysujukim** [JerrelLustre/TidalFest#5]
/- Define layout structure
- Use global components
- Communicate with @JerrelLustre

**Comment by jennysujukim** [comment]
- Separate LineupData.jsx file is ready on 'home-page' branch (will update to staging branch after reviewing)

**Comment by Boyderr** [comment]
Task assigned to Emily 
- data file to map lineup needs to be moved from src to assets/data

**Comment by Boyderr** [comment]
** I've applied min-w-max on the BandButton component in LineupDay1,2,3 to prevent the text from wrapping at tablet breakpoint. This is causing the layout to break at around 370px. We could remove the min-w-max, although this causes the words to wrap at tablet breakpoint. md:min-w-max not working.

**Comment by JerrelLustre** [comment]
Will be reviewing issues that Emily had with the page and explore possible solution

**Comment by jennysujukim** [comment]
30 July: Issue closed
